// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.2
// source: GameMessage.proto

package Messages

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NavV3 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X float32 `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y float32 `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z float32 `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
}

func (x *NavV3) Reset() {
	*x = NavV3{}
	mi := &file_GameMessage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NavV3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NavV3) ProtoMessage() {}

func (x *NavV3) ProtoReflect() protoreflect.Message {
	mi := &file_GameMessage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NavV3.ProtoReflect.Descriptor instead.
func (*NavV3) Descriptor() ([]byte, []int) {
	return file_GameMessage_proto_rawDescGZIP(), []int{0}
}

func (x *NavV3) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *NavV3) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *NavV3) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

type PathTest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Paths []*NavV3 `protobuf:"bytes,1,rep,name=paths,proto3" json:"paths,omitempty"`
}

func (x *PathTest) Reset() {
	*x = PathTest{}
	mi := &file_GameMessage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PathTest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathTest) ProtoMessage() {}

func (x *PathTest) ProtoReflect() protoreflect.Message {
	mi := &file_GameMessage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathTest.ProtoReflect.Descriptor instead.
func (*PathTest) Descriptor() ([]byte, []int) {
	return file_GameMessage_proto_rawDescGZIP(), []int{1}
}

func (x *PathTest) GetPaths() []*NavV3 {
	if x != nil {
		return x.Paths
	}
	return nil
}

type PlayerPosition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X         float32 `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y         float32 `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z         float32 `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
	Fx        float32 `protobuf:"fixed32,4,opt,name=fx,proto3" json:"fx,omitempty"`
	Fy        float32 `protobuf:"fixed32,5,opt,name=fy,proto3" json:"fy,omitempty"`
	Fz        float32 `protobuf:"fixed32,6,opt,name=fz,proto3" json:"fz,omitempty"`
	PlayerId  string  `protobuf:"bytes,7,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Speed     float32 `protobuf:"fixed32,8,opt,name=speed,proto3" json:"speed,omitempty"`
	RotationY float32 `protobuf:"fixed32,9,opt,name=rotation_y,json=rotationY,proto3" json:"rotation_y,omitempty"`
}

func (x *PlayerPosition) Reset() {
	*x = PlayerPosition{}
	mi := &file_GameMessage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerPosition) ProtoMessage() {}

func (x *PlayerPosition) ProtoReflect() protoreflect.Message {
	mi := &file_GameMessage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerPosition.ProtoReflect.Descriptor instead.
func (*PlayerPosition) Descriptor() ([]byte, []int) {
	return file_GameMessage_proto_rawDescGZIP(), []int{2}
}

func (x *PlayerPosition) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PlayerPosition) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *PlayerPosition) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *PlayerPosition) GetFx() float32 {
	if x != nil {
		return x.Fx
	}
	return 0
}

func (x *PlayerPosition) GetFy() float32 {
	if x != nil {
		return x.Fy
	}
	return 0
}

func (x *PlayerPosition) GetFz() float32 {
	if x != nil {
		return x.Fz
	}
	return 0
}

func (x *PlayerPosition) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayerPosition) GetSpeed() float32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *PlayerPosition) GetRotationY() float32 {
	if x != nil {
		return x.RotationY
	}
	return 0
}

type SpawnMyPlayer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X         float32 `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y         float32 `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z         float32 `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
	RotationY float32 `protobuf:"fixed32,4,opt,name=rotation_y,json=rotationY,proto3" json:"rotation_y,omitempty"`
}

func (x *SpawnMyPlayer) Reset() {
	*x = SpawnMyPlayer{}
	mi := &file_GameMessage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpawnMyPlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpawnMyPlayer) ProtoMessage() {}

func (x *SpawnMyPlayer) ProtoReflect() protoreflect.Message {
	mi := &file_GameMessage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpawnMyPlayer.ProtoReflect.Descriptor instead.
func (*SpawnMyPlayer) Descriptor() ([]byte, []int) {
	return file_GameMessage_proto_rawDescGZIP(), []int{3}
}

func (x *SpawnMyPlayer) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *SpawnMyPlayer) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *SpawnMyPlayer) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *SpawnMyPlayer) GetRotationY() float32 {
	if x != nil {
		return x.RotationY
	}
	return 0
}

type SpawnOtherPlayer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId  string  `protobuf:"bytes,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	X         float32 `protobuf:"fixed32,2,opt,name=x,proto3" json:"x,omitempty"`
	Y         float32 `protobuf:"fixed32,3,opt,name=y,proto3" json:"y,omitempty"`
	Z         float32 `protobuf:"fixed32,4,opt,name=z,proto3" json:"z,omitempty"`
	RotationY float32 `protobuf:"fixed32,5,opt,name=rotation_y,json=rotationY,proto3" json:"rotation_y,omitempty"`
}

func (x *SpawnOtherPlayer) Reset() {
	*x = SpawnOtherPlayer{}
	mi := &file_GameMessage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpawnOtherPlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpawnOtherPlayer) ProtoMessage() {}

func (x *SpawnOtherPlayer) ProtoReflect() protoreflect.Message {
	mi := &file_GameMessage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpawnOtherPlayer.ProtoReflect.Descriptor instead.
func (*SpawnOtherPlayer) Descriptor() ([]byte, []int) {
	return file_GameMessage_proto_rawDescGZIP(), []int{4}
}

func (x *SpawnOtherPlayer) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *SpawnOtherPlayer) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *SpawnOtherPlayer) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *SpawnOtherPlayer) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *SpawnOtherPlayer) GetRotationY() float32 {
	if x != nil {
		return x.RotationY
	}
	return 0
}

type AnimatorSetFloat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AnimId    string  `protobuf:"bytes,1,opt,name=animId,proto3" json:"animId,omitempty"`
	Condition float32 `protobuf:"fixed32,2,opt,name=condition,proto3" json:"condition,omitempty"`
}

func (x *AnimatorSetFloat) Reset() {
	*x = AnimatorSetFloat{}
	mi := &file_GameMessage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnimatorSetFloat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnimatorSetFloat) ProtoMessage() {}

func (x *AnimatorSetFloat) ProtoReflect() protoreflect.Message {
	mi := &file_GameMessage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnimatorSetFloat.ProtoReflect.Descriptor instead.
func (*AnimatorSetFloat) Descriptor() ([]byte, []int) {
	return file_GameMessage_proto_rawDescGZIP(), []int{5}
}

func (x *AnimatorSetFloat) GetAnimId() string {
	if x != nil {
		return x.AnimId
	}
	return ""
}

func (x *AnimatorSetFloat) GetCondition() float32 {
	if x != nil {
		return x.Condition
	}
	return 0
}

type AnimatorSetBool struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AnimId    string `protobuf:"bytes,1,opt,name=animId,proto3" json:"animId,omitempty"`
	Condition bool   `protobuf:"varint,2,opt,name=condition,proto3" json:"condition,omitempty"`
}

func (x *AnimatorSetBool) Reset() {
	*x = AnimatorSetBool{}
	mi := &file_GameMessage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnimatorSetBool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnimatorSetBool) ProtoMessage() {}

func (x *AnimatorSetBool) ProtoReflect() protoreflect.Message {
	mi := &file_GameMessage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnimatorSetBool.ProtoReflect.Descriptor instead.
func (*AnimatorSetBool) Descriptor() ([]byte, []int) {
	return file_GameMessage_proto_rawDescGZIP(), []int{6}
}

func (x *AnimatorSetBool) GetAnimId() string {
	if x != nil {
		return x.AnimId
	}
	return ""
}

func (x *AnimatorSetBool) GetCondition() bool {
	if x != nil {
		return x.Condition
	}
	return false
}

type AnimatorSetTrigger struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AnimId string `protobuf:"bytes,1,opt,name=animId,proto3" json:"animId,omitempty"`
}

func (x *AnimatorSetTrigger) Reset() {
	*x = AnimatorSetTrigger{}
	mi := &file_GameMessage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnimatorSetTrigger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnimatorSetTrigger) ProtoMessage() {}

func (x *AnimatorSetTrigger) ProtoReflect() protoreflect.Message {
	mi := &file_GameMessage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnimatorSetTrigger.ProtoReflect.Descriptor instead.
func (*AnimatorSetTrigger) Descriptor() ([]byte, []int) {
	return file_GameMessage_proto_rawDescGZIP(), []int{7}
}

func (x *AnimatorSetTrigger) GetAnimId() string {
	if x != nil {
		return x.AnimId
	}
	return ""
}

type ChatMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sender  string `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_GameMessage_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_GameMessage_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_GameMessage_proto_rawDescGZIP(), []int{8}
}

func (x *ChatMessage) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type LoginMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId string `protobuf:"bytes,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
}

func (x *LoginMessage) Reset() {
	*x = LoginMessage{}
	mi := &file_GameMessage_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginMessage) ProtoMessage() {}

func (x *LoginMessage) ProtoReflect() protoreflect.Message {
	mi := &file_GameMessage_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginMessage.ProtoReflect.Descriptor instead.
func (*LoginMessage) Descriptor() ([]byte, []int) {
	return file_GameMessage_proto_rawDescGZIP(), []int{9}
}

func (x *LoginMessage) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type LogoutMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId string `protobuf:"bytes,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
}

func (x *LogoutMessage) Reset() {
	*x = LogoutMessage{}
	mi := &file_GameMessage_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutMessage) ProtoMessage() {}

func (x *LogoutMessage) ProtoReflect() protoreflect.Message {
	mi := &file_GameMessage_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutMessage.ProtoReflect.Descriptor instead.
func (*LogoutMessage) Descriptor() ([]byte, []int) {
	return file_GameMessage_proto_rawDescGZIP(), []int{10}
}

func (x *LogoutMessage) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type SpawnMonster struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X         float32 `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Z         float32 `protobuf:"fixed32,2,opt,name=z,proto3" json:"z,omitempty"`
	MonsterId int32   `protobuf:"varint,3,opt,name=monsterId,proto3" json:"monsterId,omitempty"`
	RotationY float32 `protobuf:"fixed32,4,opt,name=rotationY,proto3" json:"rotationY,omitempty"`
}

func (x *SpawnMonster) Reset() {
	*x = SpawnMonster{}
	mi := &file_GameMessage_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpawnMonster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpawnMonster) ProtoMessage() {}

func (x *SpawnMonster) ProtoReflect() protoreflect.Message {
	mi := &file_GameMessage_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpawnMonster.ProtoReflect.Descriptor instead.
func (*SpawnMonster) Descriptor() ([]byte, []int) {
	return file_GameMessage_proto_rawDescGZIP(), []int{11}
}

func (x *SpawnMonster) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *SpawnMonster) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *SpawnMonster) GetMonsterId() int32 {
	if x != nil {
		return x.MonsterId
	}
	return 0
}

func (x *SpawnMonster) GetRotationY() float32 {
	if x != nil {
		return x.RotationY
	}
	return 0
}

type MoveMonster struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X         float32 `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Z         float32 `protobuf:"fixed32,2,opt,name=z,proto3" json:"z,omitempty"`
	MonsterId int32   `protobuf:"varint,3,opt,name=monsterId,proto3" json:"monsterId,omitempty"`
}

func (x *MoveMonster) Reset() {
	*x = MoveMonster{}
	mi := &file_GameMessage_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveMonster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveMonster) ProtoMessage() {}

func (x *MoveMonster) ProtoReflect() protoreflect.Message {
	mi := &file_GameMessage_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveMonster.ProtoReflect.Descriptor instead.
func (*MoveMonster) Descriptor() ([]byte, []int) {
	return file_GameMessage_proto_rawDescGZIP(), []int{12}
}

func (x *MoveMonster) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *MoveMonster) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *MoveMonster) GetMonsterId() int32 {
	if x != nil {
		return x.MonsterId
	}
	return 0
}

type MonsterTarget struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MonsterId      int32  `protobuf:"varint,1,opt,name=monsterId,proto3" json:"monsterId,omitempty"`
	TargetPlayerId string `protobuf:"bytes,2,opt,name=targetPlayerId,proto3" json:"targetPlayerId,omitempty"`
	HasTarget      bool   `protobuf:"varint,3,opt,name=hasTarget,proto3" json:"hasTarget,omitempty"`
}

func (x *MonsterTarget) Reset() {
	*x = MonsterTarget{}
	mi := &file_GameMessage_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonsterTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonsterTarget) ProtoMessage() {}

func (x *MonsterTarget) ProtoReflect() protoreflect.Message {
	mi := &file_GameMessage_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonsterTarget.ProtoReflect.Descriptor instead.
func (*MonsterTarget) Descriptor() ([]byte, []int) {
	return file_GameMessage_proto_rawDescGZIP(), []int{13}
}

func (x *MonsterTarget) GetMonsterId() int32 {
	if x != nil {
		return x.MonsterId
	}
	return 0
}

func (x *MonsterTarget) GetTargetPlayerId() string {
	if x != nil {
		return x.TargetPlayerId
	}
	return ""
}

func (x *MonsterTarget) GetHasTarget() bool {
	if x != nil {
		return x.HasTarget
	}
	return false
}

type MonsterAttack struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MonsterId      int32   `protobuf:"varint,1,opt,name=monsterId,proto3" json:"monsterId,omitempty"`
	TargetPlayerId string  `protobuf:"bytes,2,opt,name=targetPlayerId,proto3" json:"targetPlayerId,omitempty"`
	AttackType     int32   `protobuf:"varint,3,opt,name=attackType,proto3" json:"attackType,omitempty"`
	Damage         float32 `protobuf:"fixed32,4,opt,name=damage,proto3" json:"damage,omitempty"`
}

func (x *MonsterAttack) Reset() {
	*x = MonsterAttack{}
	mi := &file_GameMessage_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonsterAttack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonsterAttack) ProtoMessage() {}

func (x *MonsterAttack) ProtoReflect() protoreflect.Message {
	mi := &file_GameMessage_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonsterAttack.ProtoReflect.Descriptor instead.
func (*MonsterAttack) Descriptor() ([]byte, []int) {
	return file_GameMessage_proto_rawDescGZIP(), []int{14}
}

func (x *MonsterAttack) GetMonsterId() int32 {
	if x != nil {
		return x.MonsterId
	}
	return 0
}

func (x *MonsterAttack) GetTargetPlayerId() string {
	if x != nil {
		return x.TargetPlayerId
	}
	return ""
}

func (x *MonsterAttack) GetAttackType() int32 {
	if x != nil {
		return x.AttackType
	}
	return 0
}

func (x *MonsterAttack) GetDamage() float32 {
	if x != nil {
		return x.Damage
	}
	return 0
}

type MonsterProjectile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MonsterId    int32   `protobuf:"varint,1,opt,name=monsterId,proto3" json:"monsterId,omitempty"`
	StartX       float32 `protobuf:"fixed32,2,opt,name=startX,proto3" json:"startX,omitempty"`
	StartZ       float32 `protobuf:"fixed32,3,opt,name=startZ,proto3" json:"startZ,omitempty"`
	TargetX      float32 `protobuf:"fixed32,4,opt,name=targetX,proto3" json:"targetX,omitempty"`
	TargetZ      float32 `protobuf:"fixed32,5,opt,name=targetZ,proto3" json:"targetZ,omitempty"`
	ProjectileId int32   `protobuf:"varint,6,opt,name=projectileId,proto3" json:"projectileId,omitempty"`
}

func (x *MonsterProjectile) Reset() {
	*x = MonsterProjectile{}
	mi := &file_GameMessage_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonsterProjectile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonsterProjectile) ProtoMessage() {}

func (x *MonsterProjectile) ProtoReflect() protoreflect.Message {
	mi := &file_GameMessage_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonsterProjectile.ProtoReflect.Descriptor instead.
func (*MonsterProjectile) Descriptor() ([]byte, []int) {
	return file_GameMessage_proto_rawDescGZIP(), []int{15}
}

func (x *MonsterProjectile) GetMonsterId() int32 {
	if x != nil {
		return x.MonsterId
	}
	return 0
}

func (x *MonsterProjectile) GetStartX() float32 {
	if x != nil {
		return x.StartX
	}
	return 0
}

func (x *MonsterProjectile) GetStartZ() float32 {
	if x != nil {
		return x.StartZ
	}
	return 0
}

func (x *MonsterProjectile) GetTargetX() float32 {
	if x != nil {
		return x.TargetX
	}
	return 0
}

func (x *MonsterProjectile) GetTargetZ() float32 {
	if x != nil {
		return x.TargetZ
	}
	return 0
}

func (x *MonsterProjectile) GetProjectileId() int32 {
	if x != nil {
		return x.ProjectileId
	}
	return 0
}

type MeteorStrikePosition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X float32 `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Z float32 `protobuf:"fixed32,2,opt,name=z,proto3" json:"z,omitempty"`
}

func (x *MeteorStrikePosition) Reset() {
	*x = MeteorStrikePosition{}
	mi := &file_GameMessage_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeteorStrikePosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeteorStrikePosition) ProtoMessage() {}

func (x *MeteorStrikePosition) ProtoReflect() protoreflect.Message {
	mi := &file_GameMessage_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeteorStrikePosition.ProtoReflect.Descriptor instead.
func (*MeteorStrikePosition) Descriptor() ([]byte, []int) {
	return file_GameMessage_proto_rawDescGZIP(), []int{16}
}

func (x *MeteorStrikePosition) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *MeteorStrikePosition) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

type MeteorStrike struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MonsterId int32                   `protobuf:"varint,1,opt,name=monsterId,proto3" json:"monsterId,omitempty"`
	Positions []*MeteorStrikePosition `protobuf:"bytes,2,rep,name=positions,proto3" json:"positions,omitempty"`
}

func (x *MeteorStrike) Reset() {
	*x = MeteorStrike{}
	mi := &file_GameMessage_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeteorStrike) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeteorStrike) ProtoMessage() {}

func (x *MeteorStrike) ProtoReflect() protoreflect.Message {
	mi := &file_GameMessage_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeteorStrike.ProtoReflect.Descriptor instead.
func (*MeteorStrike) Descriptor() ([]byte, []int) {
	return file_GameMessage_proto_rawDescGZIP(), []int{17}
}

func (x *MeteorStrike) GetMonsterId() int32 {
	if x != nil {
		return x.MonsterId
	}
	return 0
}

func (x *MeteorStrike) GetPositions() []*MeteorStrikePosition {
	if x != nil {
		return x.Positions
	}
	return nil
}

type MonsterDamage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MonsterId     int32   `protobuf:"varint,1,opt,name=monster_id,json=monsterId,proto3" json:"monster_id,omitempty"`
	Damage        float32 `protobuf:"fixed32,2,opt,name=damage,proto3" json:"damage,omitempty"`
	CurrentHp     int32   `protobuf:"varint,3,opt,name=current_hp,json=currentHp,proto3" json:"current_hp,omitempty"`
	HitPointX     float32 `protobuf:"fixed32,4,opt,name=hit_point_x,json=hitPointX,proto3" json:"hit_point_x,omitempty"`
	HitPointY     float32 `protobuf:"fixed32,5,opt,name=hit_point_y,json=hitPointY,proto3" json:"hit_point_y,omitempty"`
	HitPointZ     float32 `protobuf:"fixed32,6,opt,name=hit_point_z,json=hitPointZ,proto3" json:"hit_point_z,omitempty"`
	HitNormalX    float32 `protobuf:"fixed32,7,opt,name=hit_normal_x,json=hitNormalX,proto3" json:"hit_normal_x,omitempty"`
	HitNormalY    float32 `protobuf:"fixed32,8,opt,name=hit_normal_y,json=hitNormalY,proto3" json:"hit_normal_y,omitempty"`
	HitNormalZ    float32 `protobuf:"fixed32,9,opt,name=hit_normal_z,json=hitNormalZ,proto3" json:"hit_normal_z,omitempty"`
	HitEffectType int32   `protobuf:"varint,10,opt,name=hit_effect_type,json=hitEffectType,proto3" json:"hit_effect_type,omitempty"`
}

func (x *MonsterDamage) Reset() {
	*x = MonsterDamage{}
	mi := &file_GameMessage_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonsterDamage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonsterDamage) ProtoMessage() {}

func (x *MonsterDamage) ProtoReflect() protoreflect.Message {
	mi := &file_GameMessage_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonsterDamage.ProtoReflect.Descriptor instead.
func (*MonsterDamage) Descriptor() ([]byte, []int) {
	return file_GameMessage_proto_rawDescGZIP(), []int{18}
}

func (x *MonsterDamage) GetMonsterId() int32 {
	if x != nil {
		return x.MonsterId
	}
	return 0
}

func (x *MonsterDamage) GetDamage() float32 {
	if x != nil {
		return x.Damage
	}
	return 0
}

func (x *MonsterDamage) GetCurrentHp() int32 {
	if x != nil {
		return x.CurrentHp
	}
	return 0
}

func (x *MonsterDamage) GetHitPointX() float32 {
	if x != nil {
		return x.HitPointX
	}
	return 0
}

func (x *MonsterDamage) GetHitPointY() float32 {
	if x != nil {
		return x.HitPointY
	}
	return 0
}

func (x *MonsterDamage) GetHitPointZ() float32 {
	if x != nil {
		return x.HitPointZ
	}
	return 0
}

func (x *MonsterDamage) GetHitNormalX() float32 {
	if x != nil {
		return x.HitNormalX
	}
	return 0
}

func (x *MonsterDamage) GetHitNormalY() float32 {
	if x != nil {
		return x.HitNormalY
	}
	return 0
}

func (x *MonsterDamage) GetHitNormalZ() float32 {
	if x != nil {
		return x.HitNormalZ
	}
	return 0
}

func (x *MonsterDamage) GetHitEffectType() int32 {
	if x != nil {
		return x.HitEffectType
	}
	return 0
}

type PlayerDamage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId   string  `protobuf:"bytes,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	Damage     float32 `protobuf:"fixed32,2,opt,name=damage,proto3" json:"damage,omitempty"`
	AttackType int32   `protobuf:"varint,3,opt,name=attackType,proto3" json:"attackType,omitempty"`
	HitPointX  float32 `protobuf:"fixed32,4,opt,name=hitPointX,proto3" json:"hitPointX,omitempty"`
	HitPointY  float32 `protobuf:"fixed32,5,opt,name=hitPointY,proto3" json:"hitPointY,omitempty"`
	HitPointZ  float32 `protobuf:"fixed32,6,opt,name=hitPointZ,proto3" json:"hitPointZ,omitempty"`
}

func (x *PlayerDamage) Reset() {
	*x = PlayerDamage{}
	mi := &file_GameMessage_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerDamage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerDamage) ProtoMessage() {}

func (x *PlayerDamage) ProtoReflect() protoreflect.Message {
	mi := &file_GameMessage_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerDamage.ProtoReflect.Descriptor instead.
func (*PlayerDamage) Descriptor() ([]byte, []int) {
	return file_GameMessage_proto_rawDescGZIP(), []int{19}
}

func (x *PlayerDamage) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayerDamage) GetDamage() float32 {
	if x != nil {
		return x.Damage
	}
	return 0
}

func (x *PlayerDamage) GetAttackType() int32 {
	if x != nil {
		return x.AttackType
	}
	return 0
}

func (x *PlayerDamage) GetHitPointX() float32 {
	if x != nil {
		return x.HitPointX
	}
	return 0
}

func (x *PlayerDamage) GetHitPointY() float32 {
	if x != nil {
		return x.HitPointY
	}
	return 0
}

func (x *PlayerDamage) GetHitPointZ() float32 {
	if x != nil {
		return x.HitPointZ
	}
	return 0
}

type MonsterRotate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MonsterId int32   `protobuf:"varint,1,opt,name=monsterId,proto3" json:"monsterId,omitempty"`
	Rotation  float32 `protobuf:"fixed32,2,opt,name=rotation,proto3" json:"rotation,omitempty"`
	Duration  float32 `protobuf:"fixed32,3,opt,name=duration,proto3" json:"duration,omitempty"`
}

func (x *MonsterRotate) Reset() {
	*x = MonsterRotate{}
	mi := &file_GameMessage_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonsterRotate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonsterRotate) ProtoMessage() {}

func (x *MonsterRotate) ProtoReflect() protoreflect.Message {
	mi := &file_GameMessage_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonsterRotate.ProtoReflect.Descriptor instead.
func (*MonsterRotate) Descriptor() ([]byte, []int) {
	return file_GameMessage_proto_rawDescGZIP(), []int{20}
}

func (x *MonsterRotate) GetMonsterId() int32 {
	if x != nil {
		return x.MonsterId
	}
	return 0
}

func (x *MonsterRotate) GetRotation() float32 {
	if x != nil {
		return x.Rotation
	}
	return 0
}

func (x *MonsterRotate) GetDuration() float32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

type Point3D struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X float32 `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y float32 `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z float32 `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
}

func (x *Point3D) Reset() {
	*x = Point3D{}
	mi := &file_GameMessage_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Point3D) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point3D) ProtoMessage() {}

func (x *Point3D) ProtoReflect() protoreflect.Message {
	mi := &file_GameMessage_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point3D.ProtoReflect.Descriptor instead.
func (*Point3D) Descriptor() ([]byte, []int) {
	return file_GameMessage_proto_rawDescGZIP(), []int{21}
}

func (x *Point3D) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Point3D) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Point3D) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

type MonsterHitEffect struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MonsterId     int32    `protobuf:"varint,1,opt,name=monster_id,json=monsterId,proto3" json:"monster_id,omitempty"`
	HitPoint      *Point3D `protobuf:"bytes,2,opt,name=hit_point,json=hitPoint,proto3" json:"hit_point,omitempty"`
	HitNormal     *Point3D `protobuf:"bytes,3,opt,name=hit_normal,json=hitNormal,proto3" json:"hit_normal,omitempty"`
	HitEffectType int32    `protobuf:"varint,4,opt,name=hit_effect_type,json=hitEffectType,proto3" json:"hit_effect_type,omitempty"`
}

func (x *MonsterHitEffect) Reset() {
	*x = MonsterHitEffect{}
	mi := &file_GameMessage_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonsterHitEffect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonsterHitEffect) ProtoMessage() {}

func (x *MonsterHitEffect) ProtoReflect() protoreflect.Message {
	mi := &file_GameMessage_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonsterHitEffect.ProtoReflect.Descriptor instead.
func (*MonsterHitEffect) Descriptor() ([]byte, []int) {
	return file_GameMessage_proto_rawDescGZIP(), []int{22}
}

func (x *MonsterHitEffect) GetMonsterId() int32 {
	if x != nil {
		return x.MonsterId
	}
	return 0
}

func (x *MonsterHitEffect) GetHitPoint() *Point3D {
	if x != nil {
		return x.HitPoint
	}
	return nil
}

func (x *MonsterHitEffect) GetHitNormal() *Point3D {
	if x != nil {
		return x.HitNormal
	}
	return nil
}

func (x *MonsterHitEffect) GetHitEffectType() int32 {
	if x != nil {
		return x.HitEffectType
	}
	return 0
}

type GameMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Message:
	//
	//	*GameMessage_PlayerPosition
	//	*GameMessage_Chat
	//	*GameMessage_Login
	//	*GameMessage_SpawnMyPlayer
	//	*GameMessage_SpawnOtherPlayer
	//	*GameMessage_Logout
	//	*GameMessage_PathTest
	//	*GameMessage_SpawnMonster
	//	*GameMessage_MoveMonster
	//	*GameMessage_MonsterTarget
	//	*GameMessage_MonsterAttack
	//	*GameMessage_MonsterProjectile
	//	*GameMessage_MeteorStrike
	//	*GameMessage_MonsterDamage
	//	*GameMessage_PlayerDamage
	//	*GameMessage_MonsterRotate
	//	*GameMessage_MonsterHitEffect
	Message isGameMessage_Message `protobuf_oneof:"message"`
}

func (x *GameMessage) Reset() {
	*x = GameMessage{}
	mi := &file_GameMessage_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameMessage) ProtoMessage() {}

func (x *GameMessage) ProtoReflect() protoreflect.Message {
	mi := &file_GameMessage_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameMessage.ProtoReflect.Descriptor instead.
func (*GameMessage) Descriptor() ([]byte, []int) {
	return file_GameMessage_proto_rawDescGZIP(), []int{23}
}

func (m *GameMessage) GetMessage() isGameMessage_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (x *GameMessage) GetPlayerPosition() *PlayerPosition {
	if x, ok := x.GetMessage().(*GameMessage_PlayerPosition); ok {
		return x.PlayerPosition
	}
	return nil
}

func (x *GameMessage) GetChat() *ChatMessage {
	if x, ok := x.GetMessage().(*GameMessage_Chat); ok {
		return x.Chat
	}
	return nil
}

func (x *GameMessage) GetLogin() *LoginMessage {
	if x, ok := x.GetMessage().(*GameMessage_Login); ok {
		return x.Login
	}
	return nil
}

func (x *GameMessage) GetSpawnMyPlayer() *SpawnMyPlayer {
	if x, ok := x.GetMessage().(*GameMessage_SpawnMyPlayer); ok {
		return x.SpawnMyPlayer
	}
	return nil
}

func (x *GameMessage) GetSpawnOtherPlayer() *SpawnOtherPlayer {
	if x, ok := x.GetMessage().(*GameMessage_SpawnOtherPlayer); ok {
		return x.SpawnOtherPlayer
	}
	return nil
}

func (x *GameMessage) GetLogout() *LogoutMessage {
	if x, ok := x.GetMessage().(*GameMessage_Logout); ok {
		return x.Logout
	}
	return nil
}

func (x *GameMessage) GetPathTest() *PathTest {
	if x, ok := x.GetMessage().(*GameMessage_PathTest); ok {
		return x.PathTest
	}
	return nil
}

func (x *GameMessage) GetSpawnMonster() *SpawnMonster {
	if x, ok := x.GetMessage().(*GameMessage_SpawnMonster); ok {
		return x.SpawnMonster
	}
	return nil
}

func (x *GameMessage) GetMoveMonster() *MoveMonster {
	if x, ok := x.GetMessage().(*GameMessage_MoveMonster); ok {
		return x.MoveMonster
	}
	return nil
}

func (x *GameMessage) GetMonsterTarget() *MonsterTarget {
	if x, ok := x.GetMessage().(*GameMessage_MonsterTarget); ok {
		return x.MonsterTarget
	}
	return nil
}

func (x *GameMessage) GetMonsterAttack() *MonsterAttack {
	if x, ok := x.GetMessage().(*GameMessage_MonsterAttack); ok {
		return x.MonsterAttack
	}
	return nil
}

func (x *GameMessage) GetMonsterProjectile() *MonsterProjectile {
	if x, ok := x.GetMessage().(*GameMessage_MonsterProjectile); ok {
		return x.MonsterProjectile
	}
	return nil
}

func (x *GameMessage) GetMeteorStrike() *MeteorStrike {
	if x, ok := x.GetMessage().(*GameMessage_MeteorStrike); ok {
		return x.MeteorStrike
	}
	return nil
}

func (x *GameMessage) GetMonsterDamage() *MonsterDamage {
	if x, ok := x.GetMessage().(*GameMessage_MonsterDamage); ok {
		return x.MonsterDamage
	}
	return nil
}

func (x *GameMessage) GetPlayerDamage() *PlayerDamage {
	if x, ok := x.GetMessage().(*GameMessage_PlayerDamage); ok {
		return x.PlayerDamage
	}
	return nil
}

func (x *GameMessage) GetMonsterRotate() *MonsterRotate {
	if x, ok := x.GetMessage().(*GameMessage_MonsterRotate); ok {
		return x.MonsterRotate
	}
	return nil
}

func (x *GameMessage) GetMonsterHitEffect() *MonsterHitEffect {
	if x, ok := x.GetMessage().(*GameMessage_MonsterHitEffect); ok {
		return x.MonsterHitEffect
	}
	return nil
}

type isGameMessage_Message interface {
	isGameMessage_Message()
}

type GameMessage_PlayerPosition struct {
	PlayerPosition *PlayerPosition `protobuf:"bytes,1,opt,name=player_position,json=playerPosition,proto3,oneof"`
}

type GameMessage_Chat struct {
	Chat *ChatMessage `protobuf:"bytes,2,opt,name=chat,proto3,oneof"`
}

type GameMessage_Login struct {
	Login *LoginMessage `protobuf:"bytes,3,opt,name=login,proto3,oneof"`
}

type GameMessage_SpawnMyPlayer struct {
	SpawnMyPlayer *SpawnMyPlayer `protobuf:"bytes,4,opt,name=spawnMyPlayer,proto3,oneof"`
}

type GameMessage_SpawnOtherPlayer struct {
	SpawnOtherPlayer *SpawnOtherPlayer `protobuf:"bytes,5,opt,name=spawnOtherPlayer,proto3,oneof"`
}

type GameMessage_Logout struct {
	Logout *LogoutMessage `protobuf:"bytes,6,opt,name=logout,proto3,oneof"`
}

type GameMessage_PathTest struct {
	PathTest *PathTest `protobuf:"bytes,7,opt,name=pathTest,proto3,oneof"`
}

type GameMessage_SpawnMonster struct {
	SpawnMonster *SpawnMonster `protobuf:"bytes,8,opt,name=spawnMonster,proto3,oneof"`
}

type GameMessage_MoveMonster struct {
	MoveMonster *MoveMonster `protobuf:"bytes,9,opt,name=moveMonster,proto3,oneof"`
}

type GameMessage_MonsterTarget struct {
	MonsterTarget *MonsterTarget `protobuf:"bytes,10,opt,name=monsterTarget,proto3,oneof"`
}

type GameMessage_MonsterAttack struct {
	MonsterAttack *MonsterAttack `protobuf:"bytes,11,opt,name=monsterAttack,proto3,oneof"`
}

type GameMessage_MonsterProjectile struct {
	MonsterProjectile *MonsterProjectile `protobuf:"bytes,12,opt,name=monsterProjectile,proto3,oneof"`
}

type GameMessage_MeteorStrike struct {
	MeteorStrike *MeteorStrike `protobuf:"bytes,13,opt,name=meteorStrike,proto3,oneof"`
}

type GameMessage_MonsterDamage struct {
	MonsterDamage *MonsterDamage `protobuf:"bytes,14,opt,name=monsterDamage,proto3,oneof"`
}

type GameMessage_PlayerDamage struct {
	PlayerDamage *PlayerDamage `protobuf:"bytes,15,opt,name=playerDamage,proto3,oneof"`
}

type GameMessage_MonsterRotate struct {
	MonsterRotate *MonsterRotate `protobuf:"bytes,16,opt,name=monsterRotate,proto3,oneof"`
}

type GameMessage_MonsterHitEffect struct {
	MonsterHitEffect *MonsterHitEffect `protobuf:"bytes,17,opt,name=monsterHitEffect,proto3,oneof"`
}

func (*GameMessage_PlayerPosition) isGameMessage_Message() {}

func (*GameMessage_Chat) isGameMessage_Message() {}

func (*GameMessage_Login) isGameMessage_Message() {}

func (*GameMessage_SpawnMyPlayer) isGameMessage_Message() {}

func (*GameMessage_SpawnOtherPlayer) isGameMessage_Message() {}

func (*GameMessage_Logout) isGameMessage_Message() {}

func (*GameMessage_PathTest) isGameMessage_Message() {}

func (*GameMessage_SpawnMonster) isGameMessage_Message() {}

func (*GameMessage_MoveMonster) isGameMessage_Message() {}

func (*GameMessage_MonsterTarget) isGameMessage_Message() {}

func (*GameMessage_MonsterAttack) isGameMessage_Message() {}

func (*GameMessage_MonsterProjectile) isGameMessage_Message() {}

func (*GameMessage_MeteorStrike) isGameMessage_Message() {}

func (*GameMessage_MonsterDamage) isGameMessage_Message() {}

func (*GameMessage_PlayerDamage) isGameMessage_Message() {}

func (*GameMessage_MonsterRotate) isGameMessage_Message() {}

func (*GameMessage_MonsterHitEffect) isGameMessage_Message() {}

var File_GameMessage_proto protoreflect.FileDescriptor

var file_GameMessage_proto_rawDesc = []byte{
	0x0a, 0x11, 0x47, 0x61, 0x6d, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x61, 0x6d, 0x65, 0x22, 0x31, 0x0a, 0x05, 0x4e, 0x61, 0x76,
	0x56, 0x33, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x78,
	0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x79, 0x12, 0x0c,
	0x0a, 0x01, 0x7a, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x7a, 0x22, 0x2d, 0x0a, 0x08,
	0x50, 0x61, 0x74, 0x68, 0x54, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x05, 0x70, 0x61, 0x74, 0x68,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x4e,
	0x61, 0x76, 0x56, 0x33, 0x52, 0x05, 0x70, 0x61, 0x74, 0x68, 0x73, 0x22, 0xbc, 0x01, 0x0a, 0x0e,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0c,
	0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x79, 0x12, 0x0c, 0x0a, 0x01, 0x7a, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x7a, 0x12, 0x0e, 0x0a, 0x02, 0x66, 0x78, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x02, 0x66, 0x78, 0x12, 0x0e, 0x0a, 0x02, 0x66, 0x79, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x02, 0x66, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x66, 0x7a, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x02, 0x66, 0x7a, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x70, 0x65, 0x65, 0x64, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x73, 0x70, 0x65, 0x65, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x72,
	0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x79, 0x18, 0x09, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x09, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x59, 0x22, 0x58, 0x0a, 0x0d, 0x53, 0x70,
	0x61, 0x77, 0x6e, 0x4d, 0x79, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x0c, 0x0a, 0x01, 0x78,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x79, 0x12, 0x0c, 0x0a, 0x01, 0x7a, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x01, 0x7a, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x5f, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x72, 0x6f, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x59, 0x22, 0x77, 0x0a, 0x10, 0x53, 0x70, 0x61, 0x77, 0x6e, 0x4f, 0x74, 0x68,
	0x65, 0x72, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x79,
	0x12, 0x0c, 0x0a, 0x01, 0x7a, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x7a, 0x12, 0x1d,
	0x0a, 0x0a, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x79, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x09, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x59, 0x22, 0x48, 0x0a,
	0x10, 0x41, 0x6e, 0x69, 0x6d, 0x61, 0x74, 0x6f, 0x72, 0x53, 0x65, 0x74, 0x46, 0x6c, 0x6f, 0x61,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6e, 0x69, 0x6d, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x61, 0x6e, 0x69, 0x6d, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6f, 0x6e,
	0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x63, 0x6f,
	0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x47, 0x0a, 0x0f, 0x41, 0x6e, 0x69, 0x6d, 0x61,
	0x74, 0x6f, 0x72, 0x53, 0x65, 0x74, 0x42, 0x6f, 0x6f, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6e,
	0x69, 0x6d, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x6e, 0x69, 0x6d,
	0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x22, 0x2c, 0x0a, 0x12, 0x41, 0x6e, 0x69, 0x6d, 0x61, 0x74, 0x6f, 0x72, 0x53, 0x65, 0x74, 0x54,
	0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6e, 0x69, 0x6d, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x6e, 0x69, 0x6d, 0x49, 0x64, 0x22, 0x3f,
	0x0a, 0x0b, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73,
	0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22,
	0x2a, 0x0a, 0x0c, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x22, 0x2b, 0x0a, 0x0d, 0x4c,
	0x6f, 0x67, 0x6f, 0x75, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x22, 0x66, 0x0a, 0x0c, 0x53, 0x70, 0x61, 0x77,
	0x6e, 0x4d, 0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x7a, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x01, 0x7a, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72, 0x49,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6d, 0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x59, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x59,
	0x22, 0x47, 0x0a, 0x0b, 0x4d, 0x6f, 0x76, 0x65, 0x4d, 0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72, 0x12,
	0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a,
	0x01, 0x7a, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x7a, 0x12, 0x1c, 0x0a, 0x09, 0x6d,
	0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09,
	0x6d, 0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72, 0x49, 0x64, 0x22, 0x73, 0x0a, 0x0d, 0x4d, 0x6f, 0x6e,
	0x73, 0x74, 0x65, 0x72, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x6f,
	0x6e, 0x73, 0x74, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6d,
	0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x0e, 0x74, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0e, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x1c, 0x0a, 0x09, 0x68, 0x61, 0x73, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x09, 0x68, 0x61, 0x73, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x22, 0x8d,
	0x01, 0x0a, 0x0d, 0x4d, 0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72, 0x41, 0x74, 0x74, 0x61, 0x63, 0x6b,
	0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x09, 0x6d, 0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72, 0x49, 0x64, 0x12, 0x26,
	0x0a, 0x0e, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x74, 0x74, 0x61, 0x63, 0x6b,
	0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x61, 0x74, 0x74, 0x61,
	0x63, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x61, 0x6d, 0x61, 0x67, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x64, 0x61, 0x6d, 0x61, 0x67, 0x65, 0x22, 0xb9,
	0x01, 0x0a, 0x11, 0x4d, 0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63,
	0x74, 0x69, 0x6c, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6d, 0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x72, 0x74, 0x58, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x06, 0x73, 0x74, 0x61, 0x72, 0x74, 0x58, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x5a, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x5a, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x58, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x07, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x58, 0x12, 0x18, 0x0a, 0x07,
	0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5a, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x07, 0x74,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x5a, 0x12, 0x22, 0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63,
	0x74, 0x69, 0x6c, 0x65, 0x49, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x70, 0x72,
	0x6f, 0x6a, 0x65, 0x63, 0x74, 0x69, 0x6c, 0x65, 0x49, 0x64, 0x22, 0x32, 0x0a, 0x14, 0x4d, 0x65,
	0x74, 0x65, 0x6f, 0x72, 0x53, 0x74, 0x72, 0x69, 0x6b, 0x65, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x78,
	0x12, 0x0c, 0x0a, 0x01, 0x7a, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x7a, 0x22, 0x66,
	0x0a, 0x0c, 0x4d, 0x65, 0x74, 0x65, 0x6f, 0x72, 0x53, 0x74, 0x72, 0x69, 0x6b, 0x65, 0x12, 0x1c,
	0x0a, 0x09, 0x6d, 0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x09, 0x6d, 0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72, 0x49, 0x64, 0x12, 0x38, 0x0a, 0x09,
	0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x4d, 0x65, 0x74, 0x65, 0x6f, 0x72, 0x53, 0x74, 0x72,
	0x69, 0x6b, 0x65, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x70, 0x6f, 0x73,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0xd3, 0x02, 0x0a, 0x0d, 0x4d, 0x6f, 0x6e, 0x73, 0x74,
	0x65, 0x72, 0x44, 0x61, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x6f, 0x6e, 0x73,
	0x74, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6d, 0x6f,
	0x6e, 0x73, 0x74, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x61, 0x6d, 0x61, 0x67,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x64, 0x61, 0x6d, 0x61, 0x67, 0x65, 0x12,
	0x1d, 0x0a, 0x0a, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x68, 0x70, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x09, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x48, 0x70, 0x12, 0x1e,
	0x0a, 0x0b, 0x68, 0x69, 0x74, 0x5f, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x5f, 0x78, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x09, 0x68, 0x69, 0x74, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x58, 0x12, 0x1e,
	0x0a, 0x0b, 0x68, 0x69, 0x74, 0x5f, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x5f, 0x79, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x09, 0x68, 0x69, 0x74, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x59, 0x12, 0x1e,
	0x0a, 0x0b, 0x68, 0x69, 0x74, 0x5f, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x5f, 0x7a, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x09, 0x68, 0x69, 0x74, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x5a, 0x12, 0x20,
	0x0a, 0x0c, 0x68, 0x69, 0x74, 0x5f, 0x6e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x5f, 0x78, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x0a, 0x68, 0x69, 0x74, 0x4e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x58,
	0x12, 0x20, 0x0a, 0x0c, 0x68, 0x69, 0x74, 0x5f, 0x6e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x5f, 0x79,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0a, 0x68, 0x69, 0x74, 0x4e, 0x6f, 0x72, 0x6d, 0x61,
	0x6c, 0x59, 0x12, 0x20, 0x0a, 0x0c, 0x68, 0x69, 0x74, 0x5f, 0x6e, 0x6f, 0x72, 0x6d, 0x61, 0x6c,
	0x5f, 0x7a, 0x18, 0x09, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0a, 0x68, 0x69, 0x74, 0x4e, 0x6f, 0x72,
	0x6d, 0x61, 0x6c, 0x5a, 0x12, 0x26, 0x0a, 0x0f, 0x68, 0x69, 0x74, 0x5f, 0x65, 0x66, 0x66, 0x65,
	0x63, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x68,
	0x69, 0x74, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x22, 0xbc, 0x01, 0x0a,
	0x0c, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x44, 0x61, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x61, 0x6d,
	0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x64, 0x61, 0x6d, 0x61, 0x67,
	0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x61, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x68, 0x69, 0x74, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x58, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x68, 0x69, 0x74, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x58, 0x12,
	0x1c, 0x0a, 0x09, 0x68, 0x69, 0x74, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x59, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x09, 0x68, 0x69, 0x74, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x59, 0x12, 0x1c, 0x0a,
	0x09, 0x68, 0x69, 0x74, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x5a, 0x18, 0x06, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x09, 0x68, 0x69, 0x74, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x5a, 0x22, 0x65, 0x0a, 0x0d, 0x4d,
	0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72, 0x52, 0x6f, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1c, 0x0a, 0x09,
	0x6d, 0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x09, 0x6d, 0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x6f,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x72, 0x6f,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x22, 0x33, 0x0a, 0x07, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x33, 0x44, 0x12, 0x0c, 0x0a,
	0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x79, 0x12, 0x0c, 0x0a, 0x01, 0x7a, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x7a, 0x22, 0xb3, 0x01, 0x0a, 0x10, 0x4d, 0x6f, 0x6e, 0x73,
	0x74, 0x65, 0x72, 0x48, 0x69, 0x74, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x12, 0x1d, 0x0a, 0x0a,
	0x6d, 0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x09, 0x6d, 0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72, 0x49, 0x64, 0x12, 0x2a, 0x0a, 0x09, 0x68,
	0x69, 0x74, 0x5f, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x33, 0x44, 0x52, 0x08, 0x68,
	0x69, 0x74, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x2c, 0x0a, 0x0a, 0x68, 0x69, 0x74, 0x5f, 0x6e,
	0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x67, 0x61,
	0x6d, 0x65, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x33, 0x44, 0x52, 0x09, 0x68, 0x69, 0x74, 0x4e,
	0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x12, 0x26, 0x0a, 0x0f, 0x68, 0x69, 0x74, 0x5f, 0x65, 0x66, 0x66,
	0x65, 0x63, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d,
	0x68, 0x69, 0x74, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x22, 0xf6, 0x07,
	0x0a, 0x0b, 0x47, 0x61, 0x6d, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x3f, 0x0a,
	0x0f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x0e,
	0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x27,
	0x0a, 0x04, 0x63, 0x68, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x67,
	0x61, 0x6d, 0x65, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48,
	0x00, 0x52, 0x04, 0x63, 0x68, 0x61, 0x74, 0x12, 0x2a, 0x0a, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x4c, 0x6f,
	0x67, 0x69, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x05, 0x6c, 0x6f,
	0x67, 0x69, 0x6e, 0x12, 0x3b, 0x0a, 0x0d, 0x73, 0x70, 0x61, 0x77, 0x6e, 0x4d, 0x79, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x67, 0x61, 0x6d,
	0x65, 0x2e, 0x53, 0x70, 0x61, 0x77, 0x6e, 0x4d, 0x79, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x48,
	0x00, 0x52, 0x0d, 0x73, 0x70, 0x61, 0x77, 0x6e, 0x4d, 0x79, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x12, 0x44, 0x0a, 0x10, 0x73, 0x70, 0x61, 0x77, 0x6e, 0x4f, 0x74, 0x68, 0x65, 0x72, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x67, 0x61, 0x6d,
	0x65, 0x2e, 0x53, 0x70, 0x61, 0x77, 0x6e, 0x4f, 0x74, 0x68, 0x65, 0x72, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x48, 0x00, 0x52, 0x10, 0x73, 0x70, 0x61, 0x77, 0x6e, 0x4f, 0x74, 0x68, 0x65, 0x72,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x2d, 0x0a, 0x06, 0x6c, 0x6f, 0x67, 0x6f, 0x75, 0x74,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x4c, 0x6f,
	0x67, 0x6f, 0x75, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x06, 0x6c,
	0x6f, 0x67, 0x6f, 0x75, 0x74, 0x12, 0x2c, 0x0a, 0x08, 0x70, 0x61, 0x74, 0x68, 0x54, 0x65, 0x73,
	0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x50,
	0x61, 0x74, 0x68, 0x54, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x08, 0x70, 0x61, 0x74, 0x68, 0x54,
	0x65, 0x73, 0x74, 0x12, 0x38, 0x0a, 0x0c, 0x73, 0x70, 0x61, 0x77, 0x6e, 0x4d, 0x6f, 0x6e, 0x73,
	0x74, 0x65, 0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x67, 0x61, 0x6d, 0x65,
	0x2e, 0x53, 0x70, 0x61, 0x77, 0x6e, 0x4d, 0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72, 0x48, 0x00, 0x52,
	0x0c, 0x73, 0x70, 0x61, 0x77, 0x6e, 0x4d, 0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72, 0x12, 0x35, 0x0a,
	0x0b, 0x6d, 0x6f, 0x76, 0x65, 0x4d, 0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x4d, 0x6f,
	0x6e, 0x73, 0x74, 0x65, 0x72, 0x48, 0x00, 0x52, 0x0b, 0x6d, 0x6f, 0x76, 0x65, 0x4d, 0x6f, 0x6e,
	0x73, 0x74, 0x65, 0x72, 0x12, 0x3b, 0x0a, 0x0d, 0x6d, 0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72, 0x54,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x67, 0x61,
	0x6d, 0x65, 0x2e, 0x4d, 0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x48, 0x00, 0x52, 0x0d, 0x6d, 0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72, 0x54, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x12, 0x3b, 0x0a, 0x0d, 0x6d, 0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72, 0x41, 0x74, 0x74, 0x61,
	0x63, 0x6b, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e,
	0x4d, 0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72, 0x41, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x48, 0x00, 0x52,
	0x0d, 0x6d, 0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72, 0x41, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x12, 0x47,
	0x0a, 0x11, 0x6d, 0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74,
	0x69, 0x6c, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x61, 0x6d, 0x65,
	0x2e, 0x4d, 0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x69,
	0x6c, 0x65, 0x48, 0x00, 0x52, 0x11, 0x6d, 0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72, 0x50, 0x72, 0x6f,
	0x6a, 0x65, 0x63, 0x74, 0x69, 0x6c, 0x65, 0x12, 0x38, 0x0a, 0x0c, 0x6d, 0x65, 0x74, 0x65, 0x6f,
	0x72, 0x53, 0x74, 0x72, 0x69, 0x6b, 0x65, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x67, 0x61, 0x6d, 0x65, 0x2e, 0x4d, 0x65, 0x74, 0x65, 0x6f, 0x72, 0x53, 0x74, 0x72, 0x69, 0x6b,
	0x65, 0x48, 0x00, 0x52, 0x0c, 0x6d, 0x65, 0x74, 0x65, 0x6f, 0x72, 0x53, 0x74, 0x72, 0x69, 0x6b,
	0x65, 0x12, 0x3b, 0x0a, 0x0d, 0x6d, 0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72, 0x44, 0x61, 0x6d, 0x61,
	0x67, 0x65, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e,
	0x4d, 0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72, 0x44, 0x61, 0x6d, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52,
	0x0d, 0x6d, 0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72, 0x44, 0x61, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x38,
	0x0a, 0x0c, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x44, 0x61, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x0f,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x44, 0x61, 0x6d, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x0c, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x44, 0x61, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x3b, 0x0a, 0x0d, 0x6d, 0x6f, 0x6e, 0x73,
	0x74, 0x65, 0x72, 0x52, 0x6f, 0x74, 0x61, 0x74, 0x65, 0x18, 0x10, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x13, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x4d, 0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72, 0x52, 0x6f,
	0x74, 0x61, 0x74, 0x65, 0x48, 0x00, 0x52, 0x0d, 0x6d, 0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72, 0x52,
	0x6f, 0x74, 0x61, 0x74, 0x65, 0x12, 0x44, 0x0a, 0x10, 0x6d, 0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72,
	0x48, 0x69, 0x74, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x18, 0x11, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x4d, 0x6f, 0x6e, 0x73, 0x74, 0x65, 0x72, 0x48, 0x69,
	0x74, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x48, 0x00, 0x52, 0x10, 0x6d, 0x6f, 0x6e, 0x73, 0x74,
	0x65, 0x72, 0x48, 0x69, 0x74, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x42, 0x09, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x0b, 0x5a, 0x09, 0x2f, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_GameMessage_proto_rawDescOnce sync.Once
	file_GameMessage_proto_rawDescData = file_GameMessage_proto_rawDesc
)

func file_GameMessage_proto_rawDescGZIP() []byte {
	file_GameMessage_proto_rawDescOnce.Do(func() {
		file_GameMessage_proto_rawDescData = protoimpl.X.CompressGZIP(file_GameMessage_proto_rawDescData)
	})
	return file_GameMessage_proto_rawDescData
}

var file_GameMessage_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_GameMessage_proto_goTypes = []any{
	(*NavV3)(nil),                // 0: game.NavV3
	(*PathTest)(nil),             // 1: game.PathTest
	(*PlayerPosition)(nil),       // 2: game.PlayerPosition
	(*SpawnMyPlayer)(nil),        // 3: game.SpawnMyPlayer
	(*SpawnOtherPlayer)(nil),     // 4: game.SpawnOtherPlayer
	(*AnimatorSetFloat)(nil),     // 5: game.AnimatorSetFloat
	(*AnimatorSetBool)(nil),      // 6: game.AnimatorSetBool
	(*AnimatorSetTrigger)(nil),   // 7: game.AnimatorSetTrigger
	(*ChatMessage)(nil),          // 8: game.ChatMessage
	(*LoginMessage)(nil),         // 9: game.LoginMessage
	(*LogoutMessage)(nil),        // 10: game.LogoutMessage
	(*SpawnMonster)(nil),         // 11: game.SpawnMonster
	(*MoveMonster)(nil),          // 12: game.MoveMonster
	(*MonsterTarget)(nil),        // 13: game.MonsterTarget
	(*MonsterAttack)(nil),        // 14: game.MonsterAttack
	(*MonsterProjectile)(nil),    // 15: game.MonsterProjectile
	(*MeteorStrikePosition)(nil), // 16: game.MeteorStrikePosition
	(*MeteorStrike)(nil),         // 17: game.MeteorStrike
	(*MonsterDamage)(nil),        // 18: game.MonsterDamage
	(*PlayerDamage)(nil),         // 19: game.PlayerDamage
	(*MonsterRotate)(nil),        // 20: game.MonsterRotate
	(*Point3D)(nil),              // 21: game.Point3D
	(*MonsterHitEffect)(nil),     // 22: game.MonsterHitEffect
	(*GameMessage)(nil),          // 23: game.GameMessage
}
var file_GameMessage_proto_depIdxs = []int32{
	0,  // 0: game.PathTest.paths:type_name -> game.NavV3
	16, // 1: game.MeteorStrike.positions:type_name -> game.MeteorStrikePosition
	21, // 2: game.MonsterHitEffect.hit_point:type_name -> game.Point3D
	21, // 3: game.MonsterHitEffect.hit_normal:type_name -> game.Point3D
	2,  // 4: game.GameMessage.player_position:type_name -> game.PlayerPosition
	8,  // 5: game.GameMessage.chat:type_name -> game.ChatMessage
	9,  // 6: game.GameMessage.login:type_name -> game.LoginMessage
	3,  // 7: game.GameMessage.spawnMyPlayer:type_name -> game.SpawnMyPlayer
	4,  // 8: game.GameMessage.spawnOtherPlayer:type_name -> game.SpawnOtherPlayer
	10, // 9: game.GameMessage.logout:type_name -> game.LogoutMessage
	1,  // 10: game.GameMessage.pathTest:type_name -> game.PathTest
	11, // 11: game.GameMessage.spawnMonster:type_name -> game.SpawnMonster
	12, // 12: game.GameMessage.moveMonster:type_name -> game.MoveMonster
	13, // 13: game.GameMessage.monsterTarget:type_name -> game.MonsterTarget
	14, // 14: game.GameMessage.monsterAttack:type_name -> game.MonsterAttack
	15, // 15: game.GameMessage.monsterProjectile:type_name -> game.MonsterProjectile
	17, // 16: game.GameMessage.meteorStrike:type_name -> game.MeteorStrike
	18, // 17: game.GameMessage.monsterDamage:type_name -> game.MonsterDamage
	19, // 18: game.GameMessage.playerDamage:type_name -> game.PlayerDamage
	20, // 19: game.GameMessage.monsterRotate:type_name -> game.MonsterRotate
	22, // 20: game.GameMessage.monsterHitEffect:type_name -> game.MonsterHitEffect
	21, // [21:21] is the sub-list for method output_type
	21, // [21:21] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_GameMessage_proto_init() }
func file_GameMessage_proto_init() {
	if File_GameMessage_proto != nil {
		return
	}
	file_GameMessage_proto_msgTypes[23].OneofWrappers = []any{
		(*GameMessage_PlayerPosition)(nil),
		(*GameMessage_Chat)(nil),
		(*GameMessage_Login)(nil),
		(*GameMessage_SpawnMyPlayer)(nil),
		(*GameMessage_SpawnOtherPlayer)(nil),
		(*GameMessage_Logout)(nil),
		(*GameMessage_PathTest)(nil),
		(*GameMessage_SpawnMonster)(nil),
		(*GameMessage_MoveMonster)(nil),
		(*GameMessage_MonsterTarget)(nil),
		(*GameMessage_MonsterAttack)(nil),
		(*GameMessage_MonsterProjectile)(nil),
		(*GameMessage_MeteorStrike)(nil),
		(*GameMessage_MonsterDamage)(nil),
		(*GameMessage_PlayerDamage)(nil),
		(*GameMessage_MonsterRotate)(nil),
		(*GameMessage_MonsterHitEffect)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_GameMessage_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_GameMessage_proto_goTypes,
		DependencyIndexes: file_GameMessage_proto_depIdxs,
		MessageInfos:      file_GameMessage_proto_msgTypes,
	}.Build()
	File_GameMessage_proto = out.File
	file_GameMessage_proto_rawDesc = nil
	file_GameMessage_proto_goTypes = nil
	file_GameMessage_proto_depIdxs = nil
}
